import os
import boto3
import streamlit as st

# Must be the first Streamlit command
st.set_page_config(page_title="User - Chat with PDF", layout="wide")

import langchain
import langchain_core
import langchain_community
import pydantic

from langchain.chains.retrieval_qa.base import RetrievalQA
from langchain_community.vectorstores import FAISS
from langchain_aws import BedrockEmbeddings, ChatBedrock
from langchain_core.prompts import ChatPromptTemplate

AWS_REGION = os.getenv("AWS_DEFAULT_REGION", "us-east-1")
BUCKET_NAME = os.getenv("BUCKET_NAME")

# IMPORTANT:
# This must match the embedding model used in Admin.py when the FAISS index was created.
EMBEDDING_MODEL_ID = "amazon.titan-embed-text-v2:0"

# Claude chat model
LLM_MODEL_ID = "anthropic.claude-3-haiku-20240307-v1:0"

LOCAL_INDEX_NAME = "my_faiss"
LOCAL_FOLDER_PATH = "/tmp"


if not BUCKET_NAME:
    raise ValueError("BUCKET_NAME environment variable is not set")

session = boto3.Session()
credentials = session.get_credentials()
if credentials is None:
    raise ValueError("AWS credentials not found inside container")

s3_client = session.client("s3", region_name=AWS_REGION)
bedrock_client = session.client("bedrock-runtime", region_name=AWS_REGION)

bedrock_embeddings = BedrockEmbeddings(
    model_id=EMBEDDING_MODEL_ID,
    client=bedrock_client
)


def cleanup_local_index_files() -> None:
    faiss_local_path = os.path.join(LOCAL_FOLDER_PATH, f"{LOCAL_INDEX_NAME}.faiss")
    pkl_local_path = os.path.join(LOCAL_FOLDER_PATH, f"{LOCAL_INDEX_NAME}.pkl")

    if os.path.exists(faiss_local_path):
        os.remove(faiss_local_path)

    if os.path.exists(pkl_local_path):
        os.remove(pkl_local_path)


def load_index_from_s3(index_id: str):
    cleanup_local_index_files()

    faiss_local_path = os.path.join(LOCAL_FOLDER_PATH, f"{LOCAL_INDEX_NAME}.faiss")
    pkl_local_path = os.path.join(LOCAL_FOLDER_PATH, f"{LOCAL_INDEX_NAME}.pkl")

    faiss_key = f"{index_id}.faiss"
    pkl_key = f"{index_id}.pkl"

    s3_client.download_file(
        Bucket=BUCKET_NAME,
        Key=faiss_key,
        Filename=faiss_local_path,
    )

    s3_client.download_file(
        Bucket=BUCKET_NAME,
        Key=pkl_key,
        Filename=pkl_local_path,
    )

    return faiss_local_path, pkl_local_path, faiss_key, pkl_key


def get_llm():
    return ChatBedrock(
        model_id=LLM_MODEL_ID,
        client=bedrock_client,
        model_kwargs={
            "temperature": 0.1,
            "max_tokens": 800,
        },
    )


def get_prompt():
    return ChatPromptTemplate.from_messages(
        [
            (
                "system",
                "You answer questions using only the provided context. "
                "Be brief and clear. If the answer is not in the context, say 'I don't know.'",
            ),
            (
                "human",
                "Context:\n{context}\n\nQuestion:\n{question}",
            ),
        ]
    )


def build_qa_chain(vectorstore):
    llm = get_llm()
    prompt = get_prompt()

    qa = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=vectorstore.as_retriever(
            search_type="similarity",
            search_kwargs={"k": 5},
        ),
        return_source_documents=True,
        chain_type_kwargs={"prompt": prompt},
    )
    return qa


def main():
    st.header("Client Site - Chat with PDF using Bedrock, RAG, and FAISS")

    with st.expander("Version Debug"):
        st.write("langchain:", langchain.__version__)
        st.write("langchain_core:", langchain_core.__version__)
        st.write("langchain_community:", langchain_community.__version__)
        st.write("pydantic:", pydantic.__version__)
        st.write("boto3:", boto3.__version__)
        st.write("AWS region:", AWS_REGION)
        st.write("Embedding model:", EMBEDDING_MODEL_ID)
        st.write("Chat model:", LLM_MODEL_ID)

    index_id = st.text_input("Enter INDEX_ID generated by Admin app", value="").strip()

    if st.button("Load Index"):
        if not index_id:
            st.warning("Please enter a valid INDEX_ID.")
            st.stop()

        try:
            st.info("Downloading index from S3...")
            faiss_file, pkl_file, faiss_key, pkl_key = load_index_from_s3(index_id)

            st.write("Bucket:", BUCKET_NAME)
            st.write("FAISS key:", faiss_key)
            st.write("PKL key:", pkl_key)

            st.subheader("Local Files in /tmp")
            st.write(os.listdir(LOCAL_FOLDER_PATH))
            st.write(f"FAISS exists: {os.path.exists(faiss_file)}")
            st.write(f"PKL exists: {os.path.exists(pkl_file)}")

            st.info("Loading FAISS index...")
            faiss_index = FAISS.load_local(
                folder_path=LOCAL_FOLDER_PATH,
                index_name=LOCAL_INDEX_NAME,
                embeddings=bedrock_embeddings,
                allow_dangerous_deserialization=True,
            )

            st.session_state["faiss_index"] = faiss_index
            st.session_state["index_id"] = index_id

            st.success("Index loaded successfully")

        except Exception as e:
            st.error(f"Failed to load index: {str(e)}")
            st.exception(e)

    if "faiss_index" in st.session_state:
        st.success(f"Loaded INDEX_ID: {st.session_state['index_id']}")

        question = st.text_input("Ask a question from the PDF")

        if st.button("Ask Question"):
            if not question.strip():
                st.warning("Please enter a question.")
                st.stop()

            try:
                with st.spinner("Querying..."):
                    qa = build_qa_chain(st.session_state["faiss_index"])
                    result = qa.invoke({"query": question})

                    st.subheader("Answer")
                    st.write(result["result"])

                    if result.get("source_documents"):
                        st.subheader("Source Chunks")
                        for i, doc in enumerate(result["source_documents"], start=1):
                            st.markdown(f"**Chunk {i}:**")
                            st.write(doc.page_content[:1000])

            except Exception as e:
                st.error(f"Error while querying: {str(e)}")
                st.exception(e)


if __name__ == "__main__":
    main()